### ISSUE TITLE
Suggestion about documentation

### ISSUE THREAD

**Issue by danielballan** [swcarpentry/good-enough-practices-in-scientific-computing#1]
I really like this! We will use at Brookhaven National Lab, where we are trying to lead staff scientists and visiting users (also scientists) to better software practices. Responding to [your tweet soliciting feedback](https://twitter.com/gvwilson/status/665134163478073344) I have a thought about this line:

> Documentation: don't write until you have collaborators who will read it

I agree that full documentation is not a high priority when there are zero collaborators, but I think that some forms of documentation are crucial from the beginning -- thinking of module-level and function-level docstrings, as well as comments. Even if your only collaborator is yourself six months later.

Perhaps that distinction does not really fit well into the document you have in mind. Just my two cents. Thanks again for sharing this.

**Comment by gvwilson** [comment]
Thanks for the feedback - I've added a note in 5c95d5fc about the minimal documentation we can reasonably expect from people (a "what does this do?" at the head of each script).  Can you please have a look and let me know if you (dis)agree?

**Comment by danielballan** [comment]
I like the changes. Thanks again!
