### ISSUE TITLE
Line endings and encoding

### ISSUE THREAD

**Issue by jennybc** [swcarpentry/good-enough-practices-in-scientific-computing#10]
This is an area of consistent agony for me, even when collaborating with people who have bought in to plain text, version control, distributed version control, etc. It is exacerbated when I have a collaborator who has never even heard of line endings or encoding.

Those plain text files we all love? If you've got people editing or even opening/closing them on different platforms, possibly with locale set to something other than US English, things can get weird. Line endings cycle through `\n`, `\r\n`, and `\r` and "smart quotes" drive you crazy.

Then you get large and uninformative diffs or the dreaded �.

I know this is a very geeky point but I wonder if it's worth at least mentioning here.

**Comment by naupaka** [comment]
Also especially problematic with Macs and exporting from Excel to CSV.

**Comment by jennybc** [comment]
Yes @naupaka that is Agony Number One!

Even a brief mention of these issues might be good to include. Just so people know they are not Doing It Wrong, if they require some set up re: plain text files and collaboration via distributed version control

**Comment by gvwilson** [comment]
See line 139 ++

**Comment by jennybc** [comment]
My quote is under the Papers section, but applies as much or more to Data Management. That's where this hurts the most -- because unexpected changes to line endings and encoding can mess with machine readability.

**Comment by gvwilson** [comment]
Thanks - moved to the data management area.
