### ISSUE TITLE
Ordering of topics

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/good-enough-practices-in-scientific-computing#11]
One idea might be to order topics in terms of increasing complexity. Start with completely bare minimum practices, and then build to good enough. Instead of:

Version Control -> Data Management -> Software -> Papers -> Collaboration

what about (for example):

Data Management -> Software -> Papers -> Collaboration -> Version Control

The rationale is that if the data aren't preserved well, all attempts at reproducibility are off. If analyses aren't documented via scripts or otherwise, it's very hard to know how a paper gets made; collaboration is a level above individually-authored papers, and finally knowing the history of things instead of just a single state allows for tracking of provenance.

**Comment by gvwilson** [comment]
Order changed as suggested - thanks.
