### ISSUE TITLE
Reviewing and making text consistent throughout on Wednesday 5-18

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/good-enough-practices-in-scientific-computing#116]
On Wednesday (5/18), I'll be going through all the text to make it in one consistent voice. If you have any changes you'd like to make before then, please do. I'll put out a note that I'm 'locking' the text for the day (subversion style?) and then I'll PR the updated version.

**Comment by gvwilson** [comment]
+100

**Comment by tracykteal** [comment]
I read through the paper and I'll attach my handwritten notes. There is a lot of great information in this paper! Having not been involved in the initial discussion about what the goals of the paper are, who the audience is and what wanted to be included, I talked with Greg, and I'm not the best person to be making those decisions now. I wanted to add my comments though if they would be helpful. 

The paper does switch a bit in its approach between the Collaboration section and the Project Management section. The first 4 sections are rules based, and have many rules per section the last sections are more narrative. Rules can be clarifying, but with so many sections and rules per section, the narrative approach in the last few sections reads a little more clearly. 

I especially like the section on version control. I don't think I've seen a treatment of it where there are recommendations outside of something like github, and I think it's really useful. This section does a nice job of explaining this as a real option (consistent with the 'good enough' title!) but also does a great job of motivating why you would want to use version control tools. I'm not sure you need the section in the discussion about how the authors disagree. As written it seems like maybe it satisfies all the authors? And it takes something away from the broad recommendation. I think those perspectives can be taken into account in the text, but maybe phrased differently. Also, since you do have a separate Manuscript section, you could maybe take that out of the first sentence of the version control section. Version control of code, data and software and likely a different problem than version control of manuscripts and it's nice to treat them differently (although maybe whether or not to do that was part of your discussion).

I also really like the Project Organization section. Nice practical tips for how to set up a project. 

In the 'What's Not on this list' section, could it maybe be called 'Other Things to Consider' or something along those lines - something that suggests that these are the next steps along the 'good enough' pathway. I do like that all these topics are here.

The Data Management section seems like it could be a paper all on its own. In fact many whole papers have been written on this. There are still elements that would need to be filled out in this section, on things like metadata. Data and data management is really key and the foundation of a scientific project, but given how long the paper is already, it might be worth leaving that section out here and referencing other papers devoted to this topic. Again, that was where I wasn't as clear on the goals of the paper. 

On who the paper is for, there seems to be some switching between assuming a novice audience, people without much computational experience, and those who are more aware of the tools and approaches, in the language used and the topics referenced. It might be worth being clear about the audience and going through the paper with that audience in mind. 

The paper also could use some more references, and I know you're working to fill those in. In some cases pointing to existing references would mean that you don't need as much detail on a particular topic, so it could help with brevity if that's of interest. I did just go through some reference reading and collecting for our Computing Workflows for Biologists paper (http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002303) so there might be some useful overlap in references there.

These are some great topics that need to be discussed, and you've all done a nice job on this paper! I'd be happy to continue to be a behind-the-scenes person and provide comments on future versions.

**Comment by tracykteal** [comment]
Hand written comments
[Tracy_notes.pdf](https://github.com/swcarpentry/good-enough-practices-in-scientific-computing/files/287798/Tracy_notes.pdf)

https://drive.google.com/open?id=0B6m0487UGPkgV0NuNVY0VUZlYzg
