### ISSUE TITLE
Describe linking figures in Word documents

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/good-enough-practices-in-scientific-computing#117]
From @pipitone: a halfway step to reproducibility is to use links rather than embedding for images, so that the Word doc automatically updates as figures are changed.

**Comment by pipitone** [comment]
For tables we don't have the same capability of linking, so what we suggested in the workshop was to use R packages (eg stargazer and xtable) to generate the final table from the data and then copy-and-paste from html rendered by the browser (this is also wha stargazer recommends). Not ideal but less error prone than tweaking by hand and easier to transition to rmarkdown/knitr/latex docs.

**Comment by beroe** [comment]
This may be a good idea in general but I think it is a bit too specific and esoteric for this particular document...
