### ISSUE TITLE
Manuscripts section 90% vs other 90%

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/good-enough-practices-in-scientific-computing#135]
There are two mentions of 90% in section 7 on manuscripts. Should one of them read 10%?

**Comment by gvwilson** [comment]
Nope - it's an old joke ("doing the research is the first 90%; writing up is the other 90%").  I'm pushing a clarification now.

**Comment by gcapes** [comment]
Good stuff - I wasn't sure if it was a joke or not!
