### ISSUE TITLE
Clarify 'make each row an observation'

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/good-enough-practices-in-scientific-computing#138]
> Make each row an observation: Data often comes in a wide format, because that facilitated data entry or human inspection. Imagine one row per field site and then columns for measurements made at each of several time points. Be prepared to gather such columns into a variable of measurements, plus a new variable for time point.

I don't really understand that last sentence...

**Comment by jennybc** [comment]
Are we going to have any diagrams? Because something like this would help immensely here. This is borrowed from slides by @garrettgman and I suspect we can either get permission to use it or some equivalent.

<img width="651" alt="screen shot 2016-08-01 at 6 58 22 am" src="https://cloud.githubusercontent.com/assets/599454/17293385/9e43934a-57b5-11e6-930a-6b8dd8c03a73.png">

The right hand version here is what I mean by "wide". The left hand version is what I mean by "gather into variable of measurements plus a new variable for the time point" (year, in the case of the example). But we could make the diagram and the wording match exactly, obviously.

**Comment by lexnederbragt** [comment]
Lovin' it! I would swap the figures, though. Are more examples possible? I previously suggested looking at [Data Carpentry's spreadsheet lesson](http://www.datacarpentry.org/spreadsheet-ecology-lesson/), in particular http://www.datacarpentry.org/spreadsheet-ecology-lesson/01-format-data.html (and maybe http://www.datacarpentry.org/spreadsheet-ecology-lesson/02-common-mistakes.html).

**Comment by jennybc** [comment]
Are there other diagrams or potential diagrams? If we're good with the general idea, I'll take responsibility for making or getting something like the above (yes @lexnederbragt you're correct about some optimization still being possible).

**Comment by jennybc** [comment]
Re: the spreadsheet lesson. I just taught from that!

I think it's OK to keep a wide spreadsheet -- sometimes it really is easier for data entry and inspection. And then use your analytical tool to reshape. So I'd like to word this in such a way that either is OK but you need to be aware of the different formats and get facile in some way of moving between them.

**Comment by garrettgman** [comment]
Hi guys,

There are more diagrams like Jenny's first example (and Jenny's example as
well) sprinkled throughout this online chapter:

http://r4ds.had.co.nz/tidy-data.html

Garrett

**Comment by gvwilson** [comment]
Who'd like to push this over the line?

**Comment by jennybc** [comment]
I can complete this.

@garrettgman Is it easy to provide source that would allow me to make diagrams like yours but swap left and right and match an existing example of ours exactly? I would probably make something like this in Keynote, like an animal. But I can certainly do that!

Or ... I could provide excruciating detail on what I'd like and you could make one diagram for us? We'd of course acknowledge your kind assistance.

But I can cope regardless.

**Comment by garrettgman** [comment]
Thanks @jennybc. I just sent the keynote to you via email.

**Comment by jennybc** [comment]
Thanks @garrettgman, my fellow Keynote animal. At least I'll know exactly how to edit it!

**Comment by jennybc** [comment]
Oh @gvwilson I just noticed I failed to snip out just the bit you need from that PNG. Are you in a position to do that or shall I?

**Comment by gvwilson** [comment]
I'm not sure what "just the bit you" is - can you please do that and go 
ahead and push the change directly (no need for a PR)?

**Comment by jennybc** [comment]
@gvwilson OK done.
