### ISSUE TITLE
Comments re data management

### ISSUE THREAD

**Issue by swaldman3** [swcarpentry/good-enough-practices-in-scientific-computing#14]
As the "default" scenario, I agree that this section as it is is good advice. I think it needs to be acknowledged that there will be divergences that can still be good practice.

A few examples (not necessary for inclusion, they might be too much detail):
- Where a very large amount of data is being received, and it's received in a format that is unnecessarily storage-inefficient or computationally intensive to do anything with, I think it may be justified to transform it for storage (with the procedure clearly documented, and in most cases lossless).
- Relatedly, where normalisation, or other pre-processing, is computationally expensive, it may make sense to store the intermediate, processed, data as well as the original. Arguably this is consistent with the recommendation to treat normalisation as a processing step, so long as things are set up so that this step isn't repeated unnecessarily.
- Again, for large sets of synthesised data, text files are very storage-inefficient. HDF5 is an open large-file binary format that is already noted, but some fields will have other customary standards, e.g. netCDF. It makes sense to adopt the same as the field. The comments on metadata (in another issue) become especially important here.
- In some cases it may also make sense to store data (original or generated) in a database rather than as naked files.

Not saying that these examples should be listed - more that the recommendations given are examples to which common sense / judgement should be applied.

**Comment by gvwilson** [comment]
@swaldman3 please see #30.
