### ISSUE TITLE
Ship it

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/good-enough-practices-in-scientific-computing#143]
Please add a :+1: or :-1: to this issue.

**Comment by lexnederbragt** [comment]
Are we going to address the last fixme? 

> fixme{KC}{Add pointers to papers or projects that follow these rules.}

I'm OK either way.

**Comment by gvwilson** [comment]
Thank you all - this will ship on Monday, August 29, 2016 unless someone demurs between now and then.
