### ISSUE TITLE
acknowledgements

### ISSUE THREAD

**Issue by jennybc** [swcarpentry/good-enough-practices-in-scientific-computing#144]
Seems like we need to acknowledge a few people. Shall we add such a section to the main manuscript or do it somewhere in this repo or ???

@gvwilson

**Comment by gvwilson** [comment]
:+1: to adding a section to the paper. Whose name should be in it?
- Steve Haddock
- Arjun Raj
- Stephen Turner
- Elizabeth Wickes

Please add others.

**Comment by jennybc** [comment]
Garrett Grolemund
