### ISSUE TITLE
Give instructions for updating the manuscript/website

### ISSUE THREAD

**Issue by jennybc** [swcarpentry/good-enough-practices-in-scientific-computing#148]
@gvwilson Here or in the repo itself, will you say exactly what you do when you update the manuscript/website (e.g. the actions associated with a commit like f28b7867068e88689a5e3be3a1ef47ad8b6c4692)? So others of us can do this as well. Or perhaps we could automate some bit(s) even more with travis? I am already doing `make pdf` but I think you must do more to update `index.md`?

**Comment by gvwilson** [comment]
I regenerated index.md using Pandoc, then hand-edited to get the damn 
bibliographic citations right - Pandoc doesn't appear to have an option 
to generate 100% GitHub Pages-compatible Markdown.

**Comment by jennybc** [comment]
That is unfortunate. But OK then. In that case, will you take a look at my PR #149 and, if you're content, merge and regenerate PDF and `index.md`? That's all I've got.

**Comment by gvwilson** [comment]
Yup.  I'm also exploring better automated LaTeX-to-GHP-Markdown solutions.
Thanks,
Greg
