### ISSUE TITLE
Who is this written for?

### ISSUE THREAD

**Issue by BernhardKonrad** [swcarpentry/good-enough-practices-in-scientific-computing#15]
Maybe it could be clarified what kind of researcher is addressed here. If it's only me working away on my paper, the results of which I want to be reproducible in the end, then several of the suggested rules sound unreasonable restrictive. E.g. why would I need to track changes on my manuscript draft if it's only me editing anyway?

**Comment by gvwilson** [comment]
@BernhardKonrad please see #31.

**Comment by BernhardKonrad** [comment]
Great, that helps. I'm still not convinced about the necessity to track the manuscript for a single author. In general I think these requirements are pretty high for being a minimum. I would gladly be convinced of the opposite.

**Comment by gvwilson** [comment]
The reviews I'm getting on this outline, and the ease of doing 
pre-commit review, convinces me.

**Comment by BernhardKonrad** [comment]
Ok, that's because you have friends who care about and understand what you are writing. This intersection is often empty for, say, a grad student.

**Comment by gvwilson** [comment]
Maybe if we provide better tools, we can help fix that :-)

**Comment by BernhardKonrad** [comment]
That would convince me :)

**Comment by gvwilson** [comment]
@BernhardKonrad Please see #42.

**Comment by pdebuyl** [comment]
Also, collaboration with your former self is important. Typically, I like to `git diff` my paper between first submitted and current versions. This allows to prepare a list of changes for the reply to referees, for instance.
