### ISSUE TITLE
Change main URL

### ISSUE THREAD

**Issue by jennybc** [swcarpentry/good-enough-practices-in-scientific-computing#151]
Propose the URL that's associated with this repo be the web-by thing, instead of the PDF.

So this:

http://swcarpentry.github.io/good-enough-practices-in-scientific-computing/

instead of this:

https://github.com/swcarpentry/good-enough-practices-in-scientific-computing/blob/gh-pages/good-enough-practices-for-scientific-computing.pdf

I think only @gvwilson can do this. Also presumes that the web-by thing is up-to-date.

**Comment by gvwilson** [comment]
Done.
