### ISSUE TITLE
git-lfs for data

### ISSUE THREAD

**Issue by jennybc** [swcarpentry/good-enough-practices-in-scientific-computing#156]
Recording/moving a twitter conversation here w/o 140 character limit.

From Bjørn Fjukstad (github @fjukstad, twitter [@fjukstad](https://twitter.com/fjukstad)) via [Twitter](https://twitter.com/Fjukstad/status/771714440869928960):

> great read, but why not git-lfs for version control of datasets?

I replied with this link: [GitHub’s Large File Storage is no panacea for Open Source — quite the opposite](https://medium.com/@megastep/github-s-large-file-storage-is-no-panacea-for-open-source-quite-the-opposite-12c0e16a9a91#.yhl1pd8cg).

Bjørn pointed out that article is about storing large files on GitHub.com specifically. It's not necessarily a reason to abandon git-lfs. Recommended [this list of alternative implementations](https://github.com/github/git-lfs/wiki/Implementations) and http://www.pachyderm.io.

My 2 cents: if it's not something all of **us authors** are using routinely, then it's not right for this particular paper. We even dropped many things we do (version control! tests!), in order to focus on people just entering the on-ramp.

But I like to capture these discussions for ... edification, future articles, whatever. I agree that change tracking for data, at both the pro and amateur levels, is not at all sorted out. Thanks @fjukstad.

**Comment by karthik** [comment]
Weighing in with minimal context but I agree completely. It holds other people (usually novices) to an unrealistic standard that we ourselves don't practice. It's good to separate
_here are things we do_
_here are things we would like to someday do if they work and people are willing to use them_

**Comment by lexnederbragt** [comment]
Here is the 140 character-limited starting point:  https://twitter.com/lexnederbragt/timelines/771781985798946816

**Comment by jennybc** [comment]
As @fjukstad points out on twitter, this could be added to "what we left out".

**Comment by fjukstad** [comment]
Hey! 

First off: Great read, lot's of good points to take home! 

I agree that version control of datasets (especially intermediate data) isn't really a mainstream thing yet, but I believe that it's a step towards reproducible research. E.g. if you're analyzing RNA seq data through a pipeline with multiple stages. Keeping the intermediate data (and results) under version control would simplify the process of making your results reproducible even if you update a tool in the middle of the pipeline. With these new tools such as [git-lfs](http://git-lfs.github.com) and [pachyderm](https://github.com/pachyderm) I think that it's something for readers to be aware of!

**Comment by jennybc** [comment]
I have RNA seq data in Git and on GitHub. Not the raw data, of course, but once I had it in a differential analysis pipeline. Yes it's awkward. But the datasets get progressively smaller as you move them through the analysis, so luckily the bits that are changing the most are also the smallest.

**Comment by den-run-ai** [comment]
I have not looked at pachyderm too closely, but listened the podcast about it and it has a lot of support for data engineering workflows. Anyway for machine learning workflow DVC looks more applicable than git-lfs or pachyderm:

https://github.com/iterative/dvc

Disclaimer: I have a bit of bias, because DVC is written in Python and by Russian-speaking developers.
