### ISSUE TITLE
relational theory vocabulary 

### ISSUE THREAD

**Issue by benmarwick** [swcarpentry/good-enough-practices-in-scientific-computing#16]
This looks like it's going to be the kind of paper that will be required reading for graduate students in many disciplines, which would be great.

Just a few small suggestions:
- I'm guessing that 'atomic values' has something to do with tidy data, but there's a risk that it might be skipped over by people not in nuclear engineering. Can it be replaced with something a bit more plain English?
- 'normalised' might have the same issue
- I wonder if there might be scope to mention repositories, perhaps in the 'data' section? Sharing is implied by the mention of licenses in the 'collaboration' section, but if the files never leave the researcher's computer, then we're missing out on much of the benefits and return on that effort. Would it be relevant to add something like 'submit the data and code files to a reputable DOI-issuing repository so that others can freely access the files.'?

**Comment by beroe** [comment]
I totally agree about `atomic` and `normalized`

**Comment by lexnederbragt** [comment]
+1 for `atomic`, `normalized` and `submit data and code`

**Comment by gvwilson** [comment]
See #32 - @benmarwick @beroe @lexnederbragt comments welcome.
