### ISSUE TITLE
bin vs src

### ISSUE THREAD

**Issue by kcranston** [swcarpentry/good-enough-practices-in-scientific-computing#169]
We recommend that source code (anything edited directly) goes in `src/`and external scripts or compiled programs go in `bin/`. One of our reviewers found this confusing and inconsistent: 

_"Restricting bin/ to external scripts and executables means that any directly interpreted scripts or .sql that are a part of the project would be executed from src/."_

Thoughts? Do we want to modify the text, or justify our stance on bin vs src?

**Comment by jennybc** [comment]
Where can I find these reviews?

**Comment by kcranston** [comment]
Greg posted the reviews to the gepsc mailing list.

**Comment by jkitzes** [comment]
The above is certainly how I would do it. I can see the ambiguity to some degree, but putting an editable *.py file in `bin/`, for example, seems to make even less sense. I think that the justification was that anything that you can edit goes in `src` and anything that you don't edit (compiled files or external scripts) goes in `bin`, right? So the distinction we're making is about editability, not about executeability - if you're working in a compiled language only then these are the same, but in interpreted languages they differ.

**Comment by gvwilson** [comment]
@kcranston Please review language in current version

**Comment by kcranston** [comment]
I don't see how the current text makes clear the distinction between editable = src and non-editable = src (as opposed to internal vs external files, or compiled vs non-compiled).
