### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by BernhardKonrad** [swcarpentry/good-enough-practices-in-scientific-computing#17]
`"Tests pass"` is one of the requirements in the checklist before a merge can be done. What kind of tests? Unit tests are not on the list.

Side note: In order to `"merge"` you need branches, which are also not on the list. I suggest using `"commit"` instead.

**Comment by lexnederbragt** [comment]
I was wondering about the same thing. But is phrasing it as "The project repository contains a checklist of things that must pass before the _commit_ can be done" making sense?

**Comment by BernhardKonrad** [comment]
Well, technically that's the correct wording.
I'm just not sure if that's what we want, because we surely want to encourage committing early and committing often. I don't know how to achieve the latter without branches or messing up `master`, so hopefully someone with experience from the days of CVS and Subversion can jump in here?

**Comment by gvwilson** [comment]
Please see #34.
