### ISSUE TITLE
describe what functions are

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/good-enough-practices-in-scientific-computing#174]
In the 'decompose programs into functions' section, I tried to describe what a function is, because I think people new to programming might not know. I think the description could be improved.

Also, it might be useful to give an example of a function, just one like 'calculate_celsius' or something.

**Comment by jennybc** [comment]
I put this in a nearby comment:

> Is it helpful to mention that functions are useful for pieces of logic that are repeated (do you copy and paste this bit of code?) or that may only happen once but that are un-helpfully ugly (would you like to NOT see the gory details all the time)?
