### ISSUE TITLE
add repositories where people can find libraries

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/good-enough-practices-in-scientific-computing#176]
Added a section on what libraries are and where the could be found. Update where people find libraries for different languages and potentially add links.

Section:

"Many languages catalog the libraries in a centralized
  source, for instance R has CRAN, Python has ... and Java has ..."

**Comment by jennybc** [comment]
The best URL for CRAN:

https://cloud.r-project.org

But humans might like to prefer to interact with a website like this, that enables more directed browsing and searching of the very same CRAN packages:

https://www.r-pkg.org
