### ISSUE TITLE
more references

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/good-enough-practices-in-scientific-computing#178]
One of the reviewers noted that we need more references in the software section. There are other areas where I know there are relevant papers. It would be helpful to include them as references, both for the readers to have pointers to more useful papers, and also to show that others have recommended similar strategies. 

Ashley Shade put together a nice set of references on our [Computing Workflows for Biologists](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002303) paper, so there would be some good ones there. I also added that paper as a reference in one section and it could also be relevant in the project organization section.

**Comment by gvwilson** [comment]
Added reference to Shade & Teal, added Prag Prog reference.
