### ISSUE TITLE
links to lessons?

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/good-enough-practices-in-scientific-computing#179]
Do we want to add links to any of the relevant Software Carpentry or Data Carpentry lessons. For instance we could link to the SWC github lesson in that section. Admittedly, it seems a little like self-promotion, but we have made it clear that we are affiliated with SWC/DC, so there is context. For SWC, we can link to DOIs, for Data Carpentry it would be harder. It might also then suggest that we link to other resources for learning though. 

I think readers would appreciate the resources, but I'm 0 on this because of potential other complexities.

**Comment by gvwilson** [comment]
I don't think we should link to particular lessons for risk of making it look like we're tooting our own horn - we have several refs to DC and SWC, which is enough for people to find what they need.
