### ISSUE TITLE
Collaboration and TODO

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/good-enough-practices-in-scientific-computing#18]
Instead of

> And a notes.txt file containing the to-do list and things people really need to know

we can have

```
4. If you aren't using a issue tracker (e.g. Bugzilla, RedMine, GitLab, GitHub, BitBucket, ...) add a `TODO.txt` file containing the to-do list.
```

I think that "things people really need to know" should go into `README`.

**Comment by gvwilson** [comment]
The last note under "What's Not on This List" says "issue tracking" - it's nice to have, but people are more likely to keep a notes file up to date on solo projects.
