### ISSUE TITLE
What to do with footnotes

### ISSUE THREAD

**Issue by jkitzes** [swcarpentry/good-enough-practices-in-scientific-computing#190]
@gvwilson et al. - I'm working on the final edits to our manuscript, and it looks like we have to make a decision re: footnotes. PLoS doesn't publish footnotes, so we need to either remove them or incorporate them into the text somehow.

I'd classify our footnotes into three groups - (a) URL's that should be made into references, since they lead to "content" (e.g., Arjun Raj's blog post, software examples, etc.), (b) URL's that are just links to websites that we've mentioned (e.g., git, GitHub, etc.), and (c) Greg's jokes.

For (a), I can convert into bib references (what a pain...). For (b), we could either make references for these (note that we've got 30+) or just leave them out. For (c), I'm not sure what to do - parentheticals in text?

Suggestions?

**Comment by gvwilson** [comment]
Hi Justin,

My votes are:

a) +1 to bib'ing them.

b) leave 'em out - people can google.

c) cut ruthlessly - very few jokes are funny twice.

Thoughts from others?

**Comment by jennybc** [comment]
I can get happy with @gvwilson's plan, although I find his jokes funny every time 😃

**Comment by lexnederbragt** [comment]
I'm OK with Greg's a) and c).

On b), don't we loose to much by dropping all links? We want to help not-too-savvy researchers, and assuming they'll "just" google stuff seems suboptimal. Can we make a box/table with links to resources mentioned in the paper?

**Comment by jkitzes** [comment]
Unfortunately we're at the proof stage (or something close to it), so I don't think we can add another major float like a box. I think what I'll do, unless there are objections, is to "bib" (a) and cut (b), but be liberal about what falls into category (a). So if Google would return any ambiguity, I'll make it a reference - but I think there's only one "GitHub" out there and we won't lose too much by dropping that link, for example.

I'm a little loathe to cut (c) to be honest - even one of the reviewers liked them! We could make them parentheticals at the same location as the footnote instead?

**Comment by jkitzes** [comment]
Quick update - I went through the footnotes more carefully, and it turns out there's only one Greg joke! (The first one about email.) So we'll leave that in I think. The other Greg-based footnotes were actually asides that are useful for beginners, so I think we should leave those in for sure.

Otherwise, we'll be adding about 3 or 4 additional references to URL's.

**Comment by jkitzes** [comment]
Closed in  	d2d2d1b.
