### ISSUE TITLE
Confirm affiliations

### ISSUE THREAD

**Issue by jkitzes** [swcarpentry/good-enough-practices-in-scientific-computing#191]
@gvwilson, please either confirm that our affiliations as listed on the title page of the manuscript submission (not at the top of our own pdf but the title page that the submission system spits out) are correct, or upload them here for us to check.

You also might want to update your own email address in their system - they currently have it as gvwilson@software-carpentry.org.

**Comment by jennybc** [comment]
I'm interested to know how you're handling this @gvwilson and if it is even change-able.

Should it reflect affiliation and email at time of submission or now?

I am currently listed as:
University of British Columbia / jenny@stat.ubc.ca

But really should be:
RStudio, University of British Columbia / EMAIL

where I'm not entirely sure which email to use 🤔. UBC? Gmail? RStudio?

**Comment by gvwilson** [comment]
I'm leaving my info as it was at the time of authoring, and trusting 
that the .forward from software-carpentry.org to my personal address 
will keep working.

**Comment by jennybc** [comment]
If it is easy, I'd like to be: RStudio, University of British Columbia / jenny@rstudio.com.
But it is also OK if affiliation stays 'as is'.

**Comment by gvwilson** [comment]
I will leave my affiliation as-is - see #197 for a PR that updates @jennybc's affiliation.

**Comment by lexnederbragt** [comment]
Sorry to reopen, but is PLOS OK with such short affiliations? I usually have to add department info and address etc...

**Comment by gvwilson** [comment]
PLOS has been OK with short affiliations in the past.
