### ISSUE TITLE
Final proofread

### ISSUE THREAD

**Issue by jkitzes** [swcarpentry/good-enough-practices-in-scientific-computing#196]
Based on the email that Greg got, it appears that this is our final opportunity to proofread the manuscript (i.e., PLoS doesn't have a "proof" stage where we'll look at the formatted document again). Someone with fresh eyes may want to proofread the final pdf for typo's, grammar-o's, etc.

**Comment by lexnederbragt** [comment]
I'm done. Rereading it makes me proud again, it is a good piece of work!
