### ISSUE TITLE
papers: necessary to write in plain text

### ISSUE THREAD

**Issue by stephenturner** [swcarpentry/good-enough-practices-in-scientific-computing#2]
> Papers are written in a plain text format such as LaTeX or Markdown. ... Sadly necessary...

Greg, I'm on the same page with you. I'd love it if all the biologists, physicians, and government contractors I worked with were as excited as we are about writing in Markdown under version control through GitHub.

But try explain the notion of _compiling_ a document to an overworked physician you collaborate with. Oh, but before that, you have to explain the difference between plain text and word processing. And text editors. And markdown/LaTeX compilers. And BiBTeX. And git. And github. Etc. Meanwhile he/she is getting paged from the OR...

Point is, as much as we want to convince ourselves otherwise, when you have to collaborate with those outside the scientific computing bubble, the barrier to collaborating on papers in this framework is simply too high to overcome. Good intentions aside, it always comes down to "just give me a Word document with tracked changes," or similar. There's always a least common denominator who just isn't going to be on board for writing like this.

I think it's fine to talk about the benefits of this, as has been done elsewhere, but it would be an oversight in the _Good enough..._ paper to completely ignore the reality that sometimes you have to collaborate with folks who simply aren't going to work in this framework. So, what do you do then? And I don't think the answer is one of the many sharelatex/writelatex/overleaf/authorea/etc platforms either. I don't know the answer. I wish I did!

**Comment by jennybc** [comment]
I think the first goal is for the master copy of the manuscript (or everything?) to live in the cloud. This eliminates some huge sources of crazy:
- Emailing of versions and the constant question: which version is "master"? is "master" even a well-defined concept any more? Often it is not.
- "Versioning" via filename.
- Inability to diff or track evolution.

So, yes, plain text on GitHub is one way to go.

But I'm also having a good experience with group editing of a huge number of documents on Google Drive. I think Google Docs offers many of the features we want, but without the need to compile the manuscript.

**Comment by jennybc** [comment]
I'd be happy to make a PR with this message if it's welcome?

**Comment by gvwilson** [comment]
Yes please and thank you.

**Comment by rmflight** [comment]
One possibility is also to compile markdown to Word using Pandoc, send, and then incorporate changes oneself. I haven't had to do that yet, but I am anticipating it happening sometime soon given the entrenchment of some of my collaborators in the Office workflow.

**Comment by stephenturner** [comment]
@rmflight I've also considered this, but stopped short, wondering what I'd do when I get tracked changes from multiple coauthors back in a word document. Go back and hand-jam the changes into your Markdown source? The productivity you gained by using md->pdf is now lost, doubly.

**Comment by rmflight** [comment]
@stephenturner Yeah, I'm not sure it will truly happen unless I can convince collabs to use simple Word files that can actually be converted back to md by pandoc and diffed. But I know I have at least one collab that I don't know if they can let go of Word.

**Comment by gvwilson** [comment]
I've incorporated this thread into 5c95d5fc by saying "either text in the repo, or a Google Doc with track changes" and clarified in the header that we're only recommending practices people will actually adopt. Can you please have a look and let me know if you agree?

**Comment by jennybc** [comment]
I am happy with your wording and made some other comments on that commit.

But I still think the principle of using a distributed system might deserve more emphasis. And the main manuscript is one place where we're more willing to tolerate alternative implementations of this principle. Because it keeps all members of the collaborative team contributing productively.

**Comment by gvwilson** [comment]
See line 162 - good?
