### ISSUE TITLE
Multiples

### ISSUE THREAD

**Issue by beroe** [swcarpentry/good-enough-practices-in-scientific-computing#20]
Via email Maxime wrote:

> If you have tens of thousands of files (or more), you are probably doing it wrong. Look for archiving those files in chunks, or combining them in some way.

I agree and would extend this to variables. The most common mistake I see is `score1 =`, `score2 =`, `score3 =` 
This may be getting into the data containers discussion that was put on the "do. It mention" list at the end but I think is is a good enough guiding principle, and en easy sign that you are on the wrong track. Maybe could be folded in with the don't repeat functions part.

**Comment by gvwilson** [comment]
@beroe please review #36.
