### ISSUE TITLE
format preservation

### ISSUE THREAD

**Issue by elliewix** [swcarpentry/good-enough-practices-in-scientific-computing#21]
RE: data management items 1 and 2

"All raw data is stored in the format it came in (JPEG for photographs, WAV for birdsong recordings)"

This is a fine statement but not the complete story when dealing with proprietary formats.  Data items should be stored in both the original format (e.g. excel) but also an open format that will be supported in perpetuity (CSV/plain text), or at least able to be read long into the future.

There are some domains where everyone uses the same data format right now but that doesn't mean that researchers in 10 years will be able to use it.  Our library has some information on file formats that we share with our researchers:  http://www.library.illinois.edu/sc/services/data_management/file_formats.html

An open format is not a hard and fast rule, but it should be a format that will be stable for the long term.

**Comment by gvwilson** [comment]
Addressed in #30 - @elliewix please review.

**Comment by elliewix** [comment]
Looks good!
