### ISSUE TITLE
What's actually going to be adopted

### ISSUE THREAD

**Issue by jkitzes** [swcarpentry/good-enough-practices-in-scientific-computing#23]
Great start Greg - I think the paper meets a definite need.

I'm going to take the line at the top "The majority of our learners will actually adopt it after a workshop" seriously and literally, and go from there to a few different recommendations:

**Data Management**: Great, I think all reasonable and feasible

**Software**: Great, also all reasonable and feasible. Especially appreciate that there's no requirement for the entire pipeline to be automated, which is a worthy goal but a lot to ask a novice.

**Version Control**: Now we're getting tricky. I don't see a lot of our bootcamp graduates actually implementing version control after learning about it.

One reason of course is that Git is complicated, and they probably don't feel totally competent after just a half day tutorial, and don't feel ready to commit their files (their files! Their actual work!) to something that makes files seem to appear and disappear at will - I don't think we should underestimate the importance of how scary this looks to a novice (if something goes wrong, how will I get them back?).

Another reason, though, is that Git really starts to show its value (in my opinion) once you have the need to branch and  merge - otherwise, what's the cognitive advantage for a novice over Save As? Since we don't really focus on branch and merge, they don't always see the value. Plus, and perhaps even  more importantly, most novices don't have software projects that are large or complicated enough to benefit from branching and merging - in my experience, they're mostly linear development towards a single goal.

Anyway, my possible suggestion here is to relax this along the lines of the plain text document suggestion in the following section - should we allow people to save multiple versions manually so long as they're labeled clearly with a date and perhaps even a note as to what changed? Or could we consider an automated backup system with a time stamp, like Apple's Time Machine, to be sufficient? It comes back to the question of what exactly a novice is supposed to get out of version control - I strongly suspect that whatever it is (provenance, access to earlier copies, etc.) can probably be met manually for simple projects. I can think about fleshing this out more if desired.

**Papers**: If there's one thing even less likely to happen than version control after a bootcamp, it's switching from Word to a plain text editor. Even those of us who are in love with plain text writing struggle constantly with a world that only wants Word (collaborators and journals in particular). For a novice who can't "hack" easily, getting something like BibTex or even citeproc set up is way more of a problem than using Mendeley's or Endnote's Word plugins, and may be a complete block on this kind of switch (do we really want novices switching to plain text if they end up typing bibliographies by hand?). This is especially a problem because we don't routinely teach "best practices" for authoring papers in our novice bootcamps. I would also add, as an aside, that my personal experience suggests that a lot of the other best practices, version control in particular, lose or change substantially in value when you're talking about papers rather than code.

So then I agree with the idea here of the "or" track that doesn't use plain text. But honestly, why not emailed word docs? What is the problem that Google Docs fixes here? I'm suspicious that whatever it is, it could also be fixed by intelligent naming and saving conventions, which might be appropriate for simple projects at a novice level. I can see the benefit of an online platform for collaboration, but not everyone collaborates frequently. And very importantly, how does Google Docs play with citation management software? (Should a suggestion in this section be that people should use citation management software?)

**Comment by jttkim** [comment]
I think the practice of using version control for software should be kept. I appreciate that adopting it is onerous / causes cognitive load, but so does writing software itself. A researcher who has gotten themselves started with writing software of any description has, inevitably, also acquired some skills and mental models that will help them understand and adopt version control.

Regarding papers, on the other hand, I'm quite in favour of the suggestion to relax recommendations to a level of using any word processor and any system of keeping history. The only "hard" requirement I suggest is that figures must be incorporated _exactly_ as they are generated in the `results` directory. If that is the case, I can personally put up with any mode of working on manuscripts (even circulating Word files by email).

**Comment by gvwilson** [comment]
@jkitzes can you please have a look at the revised outline and let me know if it addresses your questions?

**Comment by jkitzes** [comment]
@gvwilson, thanks. Relaxing the requirement for version control of manuscripts seems like a good start. Otherwise though I think my above comments still stand and haven't been addressed in the new draft (not that you have to necessarily! just throwing these ideas out there).

Before reading the below, I just created a new issue #53 whose resolution should probably come before this one, since it's bigger in scope. In light of, or following, those bigger points I would still suggest a few specific changes re: version control and writing:

First, discuss the prospect of "manual" version control and when it is "good enough". I would suggest that for single file code project in which we don't expect branch or merge to happen, which I think covers a non-negligible fraction of novice use cases, "Save As" is good enough. Especially if only one or two files are actually changing, and basically everything else (the `data` and `doc` dir for example) is static. It doesn't have to be a primary recommendation, but at least should be discussed. Along with this, discuss automated backup systems like Time Machine and whether, or how, they meet the goals of the "version control" section (see above re: defining what these goals are first).

Second, either articulate exactly why Word docs aren't allowed, or allow them like Google Docs. Believe me, I'm in no way advocating or in favor of Word docs myself, but I still don't see clearly articulated here why Google Docs is "good enough" but Word docs aren't. Personally, I'd suggest allowing all of these platforms but with a clear description of how they need to be used in order to meet the goals that we have for folks who want to be "good enough". Of course that requires first articulating the goals that we have for people in the writing of manuscripts - see #53.

**Comment by jkitzes** [comment]
(Should have mentioned - I'm happy to contribute text discussing the above if desired.)

**Comment by gvwilson** [comment]
PRs are always welcome.  Regarding version control, I'll make it clearer 
that we're advocating its use in part so that the project can grow 
without needing to retool.

**Comment by jkitzes** [comment]
Thanks, working on PR's now. I'm going to retract my comment on version control above in light of the caveat that manuscripts may not be included. On the second one, could you clarify for me why you think that Word is verboten but Google Docs is not? I'll either add some discussion describing the reason or make the change that allows it in some fashion.

**Comment by jkitzes** [comment]
While I hope this will continue to be fleshed out as the manuscript moves from outline to text, the structure is in place as of ab6b17b44f77e4058238506d4b32ce070adce50e so I think we can close.
