### ISSUE TITLE
Number of files

### ISSUE THREAD

**Issue by mboisson** [swcarpentry/good-enough-practices-in-scientific-computing#24]
- If you have tens of thousands of files (or more), you are probably doing it wrong. Look for archiving those files in chunks, or combining them in some way.

On a cluster, having tens of thousands of files will be a killer, but even on a personnal computer, it will make your data management a nightmare.
I have seen users who think that having 2.5M files in a directory is "ok"...

**Comment by davidedelvento** [comment]
I will put emphasis on _probably_
While certainly at least some filesystems may have troubles with directories containing a "large" number of files, some other filesystems may be "ok". Moreover, in certain cases you simply don't have an option, or the option to consolidate these files is cumbersome enough.

So, I agree that if you have tens of thousands of files you are _probably_ doing it wrong and should look for alternatives, however in a "good enough" practice, that may be the "good enough" solution.

**Comment by gvwilson** [comment]
Martin Bähr replies:

```
i'd like to side with the users on this. 
it should be ok, and if filesystems were designed like databases then 2.5M
files would be ok, just like having a database table with 2.5M records is ok.

it is not the users fault that filesystems were not designed for their needs,
and while the users should be taught how to cope with this, i consider their
expectation that having 2.5M files in a directory is ok, in itself is actually
reasonable.
```

**Comment by gvwilson** [comment]
Karin Lagesen replies:

```
More importantly, it is quite likely to kill any backup systems that you have running. 
```
