### ISSUE TITLE
What is "good enough"?

### ISSUE THREAD

**Issue by davidedelvento** [swcarpentry/good-enough-practices-in-scientific-computing#25]
I am not native English speaker, so I may be taking this totally wrong, however I feel compelled to give this feedback. To me "Good enough" does not sound right if I understand correctly the emphasis of this document.

Sufficient Practices (despite being said in the document that isn't exactly right) and Fair Practices sound better to me. But the one that sound best to me is **Minimal Practices**.

**Comment by lexnederbragt** [comment]
I liked "minimal" at first, but then I realised that it may give the impression of implying 'if you don't stick to these, you're doing it wrong', and thus be counterproductive.

**Comment by jennybc** [comment]
I think the ["That'll do, pig." clip](https://www.youtube.com/watch?v=rjQtzV9IZ0Q) from the end of Babe captures the spirit. 🐖🐖🐖🐖🐖🐖

**Comment by pdebuyl** [comment]
"good enough" conveys the idea that the content of the article will be accessible and its recommendations feasible. It is very much in line with the intent of the article: +1

**Comment by gvwilson** [comment]
Let's stick with "good enough".

**Comment by jennybc** [comment]
You could even say this title is "good enough".
