### ISSUE TITLE
Various comments

### ISSUE THREAD

**Issue by npch** [swcarpentry/good-enough-practices-in-scientific-computing#26]
Apologies for not adding to previously opened issues on various parts of the doc - it turns out that's quite a timeconsuming workflow as soon as there are several issues.

Should the Version Control and Collaboration sections be moved up to the top of the document? I looked at the data management section and thought - where's the "make sure you have a backup" - then found it later on in version control.

I think you need a simplified description of "atomic value" as many researchers may not have come across this term.

The phrasing of "Every analysis step is represented textually (complete with parameter values)" needs to be simplified (though I agree with the practice being included). 

Under collaboration, my feel is that "permissive license" is the good practice and BSD/MIT are the examples. I'd like to see Apache added as there are legal reasons why MIT and BSD might not be good practice in some areas, but I understand if that's felt to be too much detail.

"Everything created by a human being goes under version control" - I think you should add "as soon as it is created". It's a doable step by everyone, but so often it doesn't happen.

If you're going to talk about style guidelines, you might need to talk about style guidelines more (or provide links to good guides if it's too difficult to summarise generally)

"Most programmers frown on storing generated files (because you can regenerate them)
Researchers should so that they can easily tell if generated results have changed"

Also, most programmers have never had to wait for machine time, or indeed had results that might take hours, days or weeks to generate... 

As a general point, the language in the current draft veers between aimed at the likely target audience, and requiring a background in software engineering or databases to understand. I think there's a need to ensure the language is clear and understandable to any researcher, without talking down to anyone. Happy to do a pass as a pull request once the content has settled.

**Comment by npch** [comment]
Another thing I thought of that should be added:

"Give your software to someone else to look at and try every so often"

**Comment by gvwilson** [comment]
See #38 for comment on licensing, #39 for comment on saving things right away.

**Comment by gvwilson** [comment]
Agree that the point-form outline is inconsistent in level and assumptions about readers' background - that'll all get cleaned up when it's turned into prose. (Help doing/checking will be welcome.)
