### ISSUE TITLE
No commented code

### ISSUE THREAD

**Issue by ketch** [swcarpentry/good-enough-practices-in-scientific-computing#27]
One of the most common and pernicious pitfalls of many novice programmers is that of using the comment/uncomment capability as a way to change programmatic options.  This quickly leads to confusion and bugs -- especially since it means that running the same command repeatedly on the same version of the code generates different results.  It also leads to scripts that are completely unintelligible after 1 month of disuse.  How about adding:
- Programs and scripts should contain no lines of "commented out" code.  When tempted to do this, you should usually add an if statement and new argument to the function that determines which part of the if statement will be run.  Any lines that are commented out must be actual comments.

**Comment by gvwilson** [comment]
@ketch please review #40.
