### ISSUE TITLE
Ten Simple Rules for Reproducible Computational Research

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/good-enough-practices-in-scientific-computing#28]
May I suggest this reference to be added to the list of sources of inspiration?

[Ten Simple Rules for Reproducible Computational Research](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285)

**Comment by gvwilson** [comment]
@lexnederbragt Please review #37.

**Comment by lexnederbragt** [comment]
Addressed in #37
