### ISSUE TITLE
Do not store parameters in programs

### ISSUE THREAD

**Issue by pdebuyl** [swcarpentry/good-enough-practices-in-scientific-computing#33]
This is slightly related to #27 in that, often, several choices of parameters are proposed and commented out in the code. The consequence of this is that changing the value of a parameter results in a _non clean_ version control state.

The proper solutions are either to use parameter files or command-line parameters.

**Comment by gvwilson** [comment]
@pdebuyl please review #40.

**Comment by ketch** [comment]
+1.

**Comment by pdebuyl** [comment]
Solved in #40
