### ISSUE TITLE
Expected outputs for arbitrary inputs

### ISSUE THREAD

**Issue by jfsantos** [swcarpentry/good-enough-practices-in-scientific-computing#4]
One thing that I usually do and recommend that isn't as hard as as writing a full test suite is to keep a set of arbitrary inputs and their expected outputs (a "sanity check") with the code, even if this tests the whole software and not specific functions. This is not currently covered but I think it's easy enough to follow.

I'm not sure about a standardized way for doing this, but could be just adding a `test` folder, and inside that folder a script that performs this sanity check (and optionally, a data file with the required data).

**Comment by gvwilson** [comment]
Thanks for the feedback - I added a note in 5c95d5fc to point out that Noble's paper _didn't_ have a requirement for tests of any kind, which says a lot about how much we can expect. Can you please have a look and let me know what you think?

**Comment by jfsantos** [comment]
I agree. I was thinking about projects structured for distribution and sharing with other researchers, but this document is more about a "solo", exploratory project structure.
