### ISSUE TITLE
"Papers" = "Manuscripts"?

### ISSUE THREAD

**Issue by BernhardKonrad** [swcarpentry/good-enough-practices-in-scientific-computing#41]
Maybe it's just me, but I'm confused when I read "Papers" because my first thought is "References". What the researcher is writing is not a "Paper" yet, so should it rather be called something else?
Ignore if I'm the only one who gets tripped up by the wording.

**Comment by gvwilson** [comment]
Good point - what should we call it instead to make it clear that these 
are the things the researcher is writing?

**Comment by BernhardKonrad** [comment]
Maybe as simple as "Paper drafts"?

**Comment by pdebuyl** [comment]
Why not manuscripts?

**Comment by gvwilson** [comment]
Fixed in def08b7
