### ISSUE TITLE
Clarify motivation for the reader

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/good-enough-practices-in-scientific-computing#44]
The outline is great, and covers a lot of ground. However, it is mainly concerned with the 'what and how', not so much with the 'why'. This is probably the intention anyways, but it would help the reader a lot to have a firm motivation behind all these things they read they 'should' implement. I feel it is especially difficult to motivate the use of version control, for example.

**Comment by gvwilson** [comment]
Good point - how would you motivate the other practices?

**Comment by PBarmby** [comment]
motivating factors: 

reproducibility: for Future You (when you get the referee's report a year from now), your lab-mates and collaborators (in case you leave the project), and (heaven forbid) the person who accuses you of making up your data.

efficiency: if data & files are stored in a standard way, Future You can come back to a project in 6 months and not have to spend 2 days figuring out what's what. Ditto for someone else trying to take what you've done and go in a new direction.

fix-ability: e.g. version control of code+figures(+data?) helps you figure out why Fig 4 looks different now from last week.

**Comment by gvwilson** [comment]
#47 includes @PBarmby's points - how do we motivate other sections/practices?

**Comment by lexnederbragt** [comment]
Hehe, I had just started on such a PR myself. I added a motivation subheader at the beginning for each section, and made a subheader 'Practices' for the current text. I have now added these pieces here: https://github.com/swcarpentry/good-enough-practices-in-scientific-computing/pull/47#issuecomment-158761836
