### ISSUE TITLE
Using other people's tools/code

### ISSUE THREAD

**Issue by gdevenyi** [swcarpentry/good-enough-practices-in-scientific-computing#48]
Something I run into with students in my group is their readiness to run and use the output of tools others have written without every reading or understanding the steps those tools take or why they take them.

Recently had one have to re-run over 1000 subjects through analysis because they used the wrong outputs from the preprocessing tools, rendering their results meaningless.

Perhaps there needs to be a discussion about not blindly using/accepting the outputs from something without at least trying to understand what it does?

**Comment by gvwilson** [comment]
I agree in principle, but I'm not sure what we can say other than "be 
careful" - what would you add and where?

**Comment by lexnederbragt** [comment]
It's an interesting point. The current text has an emphasis on software written by the reader, not so much on a reader using someone else's software (which is how I and many of my colleagues do most of our analysis). Perhaps something under the 'Software' section that states "treat other's software as your you would your own: make sure you understand it and that it is doing what it is supposed to do"?

**Comment by gvwilson** [comment]
@gdevenyi any thoughts on wording?
