### ISSUE TITLE
Regarding documentation

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/good-enough-practices-in-scientific-computing#5]
From Susan Miller:

Having had to return to my own undocumented or insufficiently documented projects after months or years have passed has convinced me that one should _always_ document so that someone else can understand projects. This would also be important in the event that a project unexpectedly has to be handed off to someone else.

**Comment by PBarmby** [comment]
Code-level documentation plus an overall project README is the bare minimum here, IMO. Detailed "cookbook" docs would be great but aren't going to happen in most cases.

**Comment by gvwilson** [comment]
I've added a note about docs in 5c95d5fc - please let me know what you think.
