### ISSUE TITLE
Assorted feedback

### ISSUE THREAD

**Issue by tdda** [swcarpentry/good-enough-practices-in-scientific-computing#51]
1. I think the word you're looking for adequate. De minimis would be another. Though "good enough" is earthier.
2. The <title> element on your Github page is Favourites. This is extremely unhelpful.
3. Data management recommendation 3, second point. "Every record has a unique key so that it can be selected precisely." I'm not sure about this. You're advocating creating a unique key, if there isn't one, I guess, possibly with row number if the data came in as an ordered list of records. If you're relying on the row-number anyway, you don't really need to create it as a separate field unless you're putting the data somewhere that will destroy the order. And what if there are duplicate records? Do you want to make those records different by adding unique keys? That's not always a bad thing to do, but its also not always good. Overall, it feels to me like this recommendation is only sometimes useful, and in general might cause problems as often as it avoids them.
4. Data management 5. Hard to argue against meaningful filenames, though there is a school of thought that the filename isn't a perfect location for important metadata. More importantly, beware case-insensitive file systems, which can bite you badly if you have (for example) case sensitive fieldnames and follow your recommendation here.
5. Data management 6: Not sure about the preference for CSV. The most important thing is that humans can understand the information, and cramming it into CSV and avoiding useful paragraphs of prose sounds ike a recipe for making the information less useful for humans. (Will be publishing some suggestions on this at www.tdda.info before too long.)
6. Generally, I think there's not enough about metadata/data dictionaries here. Elizabeth Wickes makes good points. Some things not included:
   - A data dictionary describing (for humans) the _meaning_ of the fields is critical for correct interpretation.
   - As well as Elizabeth's distinction, you need to be clear about the difference between metadata for transfer formats (how to read the CSV file correctly) and metadata about the content of the dataset.
   - Important things to know about CSV/flat files:
     - Encoding (prefer UTF-8)
     - Separator
     - quote character
     - Escape rules (minimally, escape character, usually backslash). But also, are embedded quotes stuttered or escaped. How are What does backslash mean: is \n a newline or an n. What about \t?
     - Are literal newlines allowed (no!)
     - How are nulls represented?
     - Other madness like Excel not bothering to include separators if the rest of the line is full of nulls.
7. Software, Point 3. <Rolls eyes.> You can choose my script lengths when you write the code. Personally, editing dozens of files because someone thinks everything needs to be split up is my idea of hell and makes projects much harder to understand. There's a happy medium, and it depends on the task. How about a gentler "split scripts into meaningful subscripts as appropriate", rather obsessing about line counts? And what if there _are_ more than half a dozen parameters? Do we cheat by making them structured? Or remove some flexibility? Or pretend the world is simpler than it is?

**Comment by gvwilson** [comment]
- Comment on unique keys addressed in 5a85d6a
- Comment on eye-rolling addressed in a5f43f5
