### ISSUE TITLE
Start with why (the goals) before the what (the practices)

### ISSUE THREAD

**Issue by jkitzes** [swcarpentry/good-enough-practices-in-scientific-computing#53]
As I look at the draft again in light of my previous comments in #23, I have a very broad comment that comes before my other specific recommendations, which is that there's no discussion (yet) of what the point of each of these practices are - we go right into what tools and practices are needed without describing what the outcome is that we're trying to generate.

For example we go right into version control without describing the point of version control _for this user group_, with their particular demands and types of projects. I'm suggesting something like learning goals for each section, essentially, to avoid having only the what without the why.

Adding a few sentences on learning goals before each header would be the simple solution, but I'd actually suggest going a step further and rewriting each of the bullet recommendations in terms of the key conceptual benefit instead of the actual practice. So have the "what we're trying to achieve" as the bullet point with the practice or the tool as the explanation.

Here's an example - here are the first 3 points in the manuscript as written:
1. Raw data should be stored exactly as it arrived (e.g., raw JPEGs for photographs)
2. All synthesized data is stored in well-defined widely-used formats:
3. All data follows a few basic rules:
   - Each value is atomic, i.e., has no sub-parts
   - Every record has a unique key so that it can be selected precisely

And here's my suggestion - read these as prefaced by "As a good enough scientific computing practitioner, your should try to..."
1. Retain all information contained in your raw data. Specific action: Maintain copies of all incoming information
2. Ensure your data is readable by as many people on as many systems as possible, now and into the future. Specific action: All synthesized data is stored in well-defined widely-used formats
3. Make every individual component of your data easy to identify and extra. Specific action: All data follows a few basic rules...

As hinted in #23, thinking this way really pushes on version control:
1. Everything created by a human being goes under version control as soon as it's created
2. The repository is mirrored on at least one machine that isn't the researcher's computer 

The question, of course is _why_ this user group, at the "good enough" stage needs version control, or if they do, what precisely are they supposed to get out of it? I would formulate these as something like:
1. Save every every version of every piece of your work, labeled with a date and a descriptive file name or supporting text file. Specific action: version control OR "Save As" for simple projects OR Time Machine backup for simple projects.
2. Back up all of your work on a second, offsite location to avoid the possibility of loss. Specific action: mirror repository OR tape drive (:P)

A similar issue applies to my question of why Google Docs is allowed but Word docs aren't. Can we articulate the key goal that the former meets and the latter doesn't? I'm having a hard time doing so, except perhaps if the issue is specific to collaboration (and even then I find it fuzzy).

I know this would be a lot of work, but I think it would be valuable. If you think it's worthwhile, I can have a go at rewriting the points in this way. But I understand that it would change/undo a lot of work to this point, so also happy not to!

**Comment by jkitzes** [comment]
Sorry, just realized this is at least partially a dupe with #44 and #47 - @gvwilson and @lexnederbragt, I'm happy to help there if desired, just let me know -

**Comment by gvwilson** [comment]
Sure - PRs with additions/changes are always welcome.

**Comment by jkitzes** [comment]
PR #56 adopts the already proposed strategy of adding a Goals section above the practices, rather than rewriting the practices.
