### ISSUE TITLE
Audience - bis

### ISSUE THREAD

**Issue by pdebuyl** [swcarpentry/good-enough-practices-in-scientific-computing#58]
Hi,

I know that the audience issue has already been raised. I think that for further comments/pull requests on the current manuscript it would help to know whether there is a distinction between the audience of the manuscript itself and the audience of the recommendations or not.

What I mean: Is the paper supposed to be accessible _and_ attractive to the lambda scientist (i.e. one that does not already follow the _good enough_ lifestyle), or is it intended for advocates of best practices?

If it is the former case, I think that one aim of the paper should be that I can drop a printout of it on a colleague's desk and have said colleague interested in reading it.
Then, the introduction should have a stronger motivational part and mention the relative novelty of computing in the history of science and the analogy to experimental practices such as the lab notebook. This content is covered in the "Best Practices" paper but I don't know whether it is planned for this one.

**Comment by gvwilson** [comment]
This paper is intended for people who _aren't_ already believers.  I 
hope that will become clearer as we expand the bullet points into prose 
- right now, the goal is to converge on what practices we're recommending.
