### ISSUE TITLE
Idea for title

### ISSUE THREAD

**Issue by jkitzes** [swcarpentry/good-enough-practices-in-scientific-computing#71]
I know that we floated a few ideas for the title of the manuscript a while back, particularly the implications of the phrase "Good Enough" - this morning I had the idea that we might consider "Pretty Good Practices for Scientific Computing" (of course making a small pun on the other PGP). Just a thought, not wedded to it.

**Comment by beroe** [comment]
I don't have a big problem with "Good enough" but if it does change I like this alternative. Nice!

**Comment by jennybc** [comment]
I like "good enough" and I like "pretty good".

**Comment by lexnederbragt** [comment]
I would still argue for ‘Good enough’ on the grounds that the paper wants to confer the message that the ‘Best practices’ from the corresponding paper may be out of reach to some, so here are a set of ‘Good enough’ practices that should be reachable for all those that want to make the effort. ‘Pretty good’ practices then sounds to me less appealing for the intended audience.

**Comment by kcranston** [comment]
I like either one. If I had to make a choice, I would stick with 'Good enough' (and I have a hard time passing over a good pun). Given a Good / Better / Best scale - 'Good enough' sounds like practices that are at least Good, while 'Pretty good' makes me think that we might be dipping into not-quite-good territory.

**Comment by jkitzes** [comment]
I'll go ahead and close this, as I think "Good Enough" has the votes and the momentum -
