### ISSUE TITLE
GitHub UI: Propose file change.. where do those go?

### ISSUE THREAD

**Issue by beroe** [swcarpentry/good-enough-practices-in-scientific-computing#76]
I made some edits earlier through the GitHub web UI, and clicked "Propose File Change" but stopped short of an actual Pull request. I was going to resume editing and wanted to start from that previous version, but don't see it...? In my github account there is a fork of the proje, but it is the original version w/o my changes.

**Comment by gvwilson** [comment]
I don't know - after our experiences using the GitHub web UI for editing during instructor training 12 months ago, I've given up on it.

**Comment by lexnederbragt** [comment]
Maybe your changes are on another branch in your fork?

**Comment by gvwilson** [comment]
I've merged your edits - thanks!
