### ISSUE TITLE
A few quick thoughts

### ISSUE THREAD

**Issue by arjunrajlab** [swcarpentry/good-enough-practices-in-scientific-computing#77]
Hi all,

Been emailing back and forth with Greg a bit, and he kindly pointed me to this document, which is really great! I have yet to go through it in great detail, but here are a few quick thoughts:
1. It might be really helpful to have an actual example (from, e.g., molecular biology and other fields) of a reproducible paper.  I have several such examples that I’d be happy to share.  This might help people see exactly what the benefits are more concretely.
2. I would perhaps avoid the use of the word “rule".  They’re more like… guidelines, after all ;).  In our lab, we often encounter some situation or another in which we bend our rules to accommodate some specific feature of the data or analysis. Perhaps also breaking down rules into absolute rules (in my lab, having all analysis come from a script is a pretty hard rule) and softer rules (in practice, duplication is fine on a limited basis, depending).
3. I really like the “rules” for software that you guys have up there.  Internally, we have arrived at essentially the same list, but only through a lot of pain.  It’s nice to have it spelled out so clearly!  Again, may be nice to have examples to show what happens.  I have a few scripts I show people in the lab and a few anecdotes I trot out to help keep them motivated to adhering to these rules.
4. I know I’ve mentioned this a few times, but I really would like to understand the motivation for promoting version control for manuscript management.  There are two separate issues here.  One is whether others will take the time to learn to use version control and programmatic manuscript generation (and the answer, for most collaborators, is a resounding no).  That is a matter of practicality.  The other is whether manuscript editing is really best served by version control at all.  I think the Google Doc solution is much better in that regard.  It is, after all, a system _designed specifically for collaborative manuscript writing_.  I think what I’m saying is that learning curve aside, I see little benefit to using version control for documents (unless very long or heavy math).  Maybe I’m wrong, but I’d like to see a coherent, well-reasoned rationale for promoting version control + markdown/LaTeX over Google Docs (which currently comes across as a backup/lite version), when I would argue that usability issues aside, Google Docs is simply the better tool for the job.  (The fact that you have tracking of all old versions of a document is simply not practically relevant, at least for all the papers I've been involved in.)  The fact that Google Docs is also about 1000x easier is just gravy :).  Also, in practice, whatever, merging back in some track changes from Word back into a Google Doc isn’t really that big a deal.  And I’ve had reasonable success getting even senior molecular biology PIs to use Google Docs.
5. Code reviews: I actually think that having someone look over code is a pretty useful thing in an analysis.  We've not yet done this formally in the lab, but it informally happens all the time, and I've been thinking about formally instituting a rule that someone has to go over all code with someone else in lab.

Anyway, just some thoughts, hope they are helpful, and happy to discuss further!
Arjun

**Comment by jennybc** [comment]
Thanks @arjunrajlab!

We are explicitly trying (aren't we, coauthors?) to NOT be dogmatic about version control for manuscript management. We mention it but also present Google Docs as a viable approach. It's true we express a preference for version control in the Git sense, over Google Docs.

Your input is very helpful.

**Comment by arjunrajlab** [comment]
Cool, I think people will appreciate not being dogmatic about version control for manuscripts. What I think would be helpful would be some _rationale_ for even the preference of version control over Google Docs. I'm totally willing to be convinced, but it will require convincing.

Indeed, I bring this up because I think in general that examples that provide motivation for the prescriptions given here would be most persuasive, at least in my scientific community.

One other minor point: perhaps swap anachronistic names like "src" and "bin" for something more descriptive? Even "code" and "binaries" would be better, I think.

**Comment by gvwilson** [comment]
- Point 2 addressed in ff9eaba
- Others have already been addressed (except citing examples).
