### ISSUE TITLE
Computationally competent

### ISSUE THREAD

**Issue by jkitzes** [swcarpentry/good-enough-practices-in-scientific-computing#86]
Putting this short note here, for lack of anywhere else obvious to put it. In the current draft, the footnote to the phrase "computationally competent" describes why that phrase was chosen, but not what it _is_. I was expecting this footnote to provide a longer discussion of what this means, perhaps with examples. Circularly, of course, someone computationally competent is someone who does what's suggested in this manuscript, but that might not be very helpful.

**Comment by gvwilson** [comment]
Closed by 52adea4
