### ISSUE TITLE
Source code not in with data

### ISSUE THREAD

**Issue by beroe** [swcarpentry/good-enough-practices-in-scientific-computing#88]
I am having an issue with my grad student putting copies of scripts in his data folders to keep everything "together". I would like to add a specific caveat against this potentially common practice, which has the dangers of _source code proliferation_ (which copy am I editing vs which one am I running?) and also makes version control difficult/impossible without extensive use of `.gitignore`. (These are genome sequence, so we can't keep raw and filtered reads in the repo, for example.)

The question is where best to put this? When we are talking about Project Organization, up from with Software, or down with Version Control. I somewhat favor with Software, but P.O. also makes a lot of sense.

**Comment by jkitzes** [comment]
The current project organization section definitely recommends different subdirectories for code and data - is there something beyond the current recommendation that you'd suggest?

**Comment by beroe** [comment]
It is definitely implicit there, but I was hoping for an explicit statement NOT to do that.

**Comment by gvwilson** [comment]
Please check the latest version (generated PDF).
