### ISSUE TITLE
textual representation

### ISSUE THREAD

**Issue by PBarmby** [swcarpentry/good-enough-practices-in-scientific-computing#9]
"Every analysis step is represented textually" -- by which you mean no analysis is done via point-and-click operations?

If so, while I agree that this is a worthy goal, I certainly know of situations where nobody has figured out how to automate a particular step of a process. Drawing "regions of interest" on medical images, or picking out the artifacts in astronomical images, are a couple of examples. This might be a case where more-than-bare-bones documentation is required.

**Comment by gvwilson** [comment]
I've added a note about this in 5c95d5fc, but it makes me a bit uncomfortable - can you please have a look and let me know what else we could reasonably expect of people?

**Comment by jduckles** [comment]
The data that come from an AOI selection with a GUI should still be a textual artifact in a 'good enough' practice. We aren't concerned so much with how the data came to be, but that we have it persisted. 

Duplicating the weather that generated a temperature log timeseries isn't going to happen, but we have a log of it. I feel the same is true of hand-digitizing an AOI, we are concerned with the artifact, not necessarily how it came to be (although there will likely be metadata about how it came to be that will be necessary to interpret it).

**Comment by gvwilson** [comment]
See line 65++ of `index.md` - good?

**Comment by jduckles** [comment]
Sure, works as a placeholder.
