### ISSUE TITLE
Manual version control. What to recommend?

### ISSUE THREAD

**Issue by beroe** [swcarpentry/good-enough-practices-in-scientific-computing#90]
I am still having an "issue" with [this commit](https://github.com/swcarpentry/good-enough-practices-in-scientific-computing/commit/2676175f0a009014c76e72442a500fc535bee32f) and would like to re-open the discussion of whether we recommend manual version control and in what detail.

My student started organizing his digital lab notebooks and source code into dated folders. Each week he creates a new folder `20160404`, copies his `notebook.md` file and his `analysis.py` script in there and starts editing. This is a nightmare for me because we now have no history of changes from the notebook and script to last week. I really feel that using the `tomato_project_001` approach is not far removed from `Thesis_final_revised2_finalfinal_v4.doc` and am reluctant to recommend it even as a stepping stone to the more intimidating world of real version control. 

If we do leave it, then that section needs to be substantially tightened, because the length seems disproportionate to the space devoted to other topics.

Thoughts?

**Comment by gvwilson** [comment]
@jkitzes and I are going to rewrite the manuscript and version control sections in parallel over the next couple of days to address this - we'd be grateful if you'd look at the changes and tell us if they address this.
