### ISSUE TITLE
Authorship order

### ISSUE THREAD

**Issue by beroe** [swcarpentry/good-enough-practices-in-scientific-computing#93]
I propose that Greg be put as first author, as he is too deferential to put himself first. Rationale is found [here](https://github.com/swcarpentry/good-enough-practices-in-scientific-computing/graphs/contributors)

**Comment by gvwilson** [comment]
Thank you, but I decline - it's someone else's turn.

**Comment by jkitzes** [comment]
Despite Greg's protestations, I'm going to second the original idea. Unfortunately for you, Greg, you've still done most of the work here, and you can't hide from the credit so easily!

Seriously though, I understand the idea of giving someone else a turn, which is appropriate when we step up and genuinely take a turn. But this was your seed idea and your work more than anyone elses, and I think that it's appropriate and correct in all senses to recognize it as such.

**Comment by kcranston** [comment]
Agree - Greg definitely did far more than the rest of us on this one.

**Comment by tracykteal** [comment]
As someone watching the commits go by, I also agree that Greg should be first. Also, I haven't done anything other than lurk on this paper, so unless there's something significant that you would still want me to do, I shouldn't be on the author list.

**Comment by lexnederbragt** [comment]
Not completely fair, but still: https://github.com/swcarpentry/good-enough-practices-in-scientific-computing/blame/gh-pages/index.md
