### ISSUE TITLE
Comments on version control from #92

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/good-enough-practices-in-scientific-computing#95]
Moved here from #92 so they don't get lost:

Re: what we really need from (in)formal VC: [1] assurance you could get back to previous version if really needed to; [2] sane coordination of edits from multiple people.

Re: VC coming from s/w world. And this is sort of why it sucks, esp. at first. Many of us are making "off-label" use of formal VC systems. 95% of the features aren't needed but clog up the UI and docs. And a few things we need aren't there.

**Comment by jennybc** [comment]
Adding point [0] re: what people need from VC (formal or not): a working definition of "previous version". For the "suffix-with-date-and-initials" crowd, that is whenever they change the filename. For the Google Doc or DropBox crowd that is (would be good to articulate). For the Git crowd, that's a commit.

**Comment by lexnederbragt** [comment]
For the Google Doc or DropBox crowd that is whatever that application decides is a version you can go back to - they are only timestamped and I don't think it is transparent when a new version is saved. Plus they don't always go back more than X versions or Y days/months.

**Comment by jennybc** [comment]
@lexnederbragt W/o really meaning to, I think this points out one of the problems with DropBox, at least and possibly Google Docs. You can look at revisions for Google Docs but I don't think user gets to declare "this is a version I might want to return to". I have no idea how Google Docs decides to bundle a group of edits together and create a revision.

**Comment by lexnederbragt** [comment]
@jennybc Exactly!

**Comment by gvwilson** [comment]
Addressed in 50310a0
