### ISSUE TITLE
Balancing lengths of sections

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/good-enough-practices-in-scientific-computing#96]
1 530
2 1436
3 881
4 818
5 1081
6 2086
7 1096
8 910

6, Version control, and perhaps 2, Data management, are significantly longer than the others. Readability would benefit from a more balanced length distribution, i.e. shrink sections 2 and 6

**Comment by jennybc** [comment]
This agrees with my self-admission to being wordy.

**Comment by gvwilson** [comment]
Current:
1. Intro: 304
2. Data Management: 1703
3. Software: 826
4. Collaboration: 713
5. Project Management: 1130
6. Version Control: 1777
7. Manuscripts: 1280
8. What We Left Out: 850

**Comment by beroe** [comment]
Assuming you want to resolve this by trimming, and not expanding?
-Steve

----- q•b -----
